#!/usr/bin/env python3
"""
Deterministic composite: apply the official IG Sabroso logo decal onto the
generated white hard-hat hero photo.

Inputs (checked into the repo, never regenerated by this script):
  - src/assets/helmet-hero-base.jpg  (AI-generated warm golden-hour hero,
                                       a plain unbranded white hard hat)
  - src/assets/logo-source.png       (exact official logo asset — same PNG
                                       used by the site header; mirrored from
                                       R2 for reproducible builds)

Output (committed as an ES6-importable image asset):
  - src/assets/helmet-hero.jpg       (base photo with the official logo
                                       compositied on the helmet crown)

The logo is NEVER redrawn, recolored, mirrored, stretched, or approximated.
It is only scaled proportionally (aspect ratio preserved) and alpha-blended
onto a fixed anchor point on the helmet crown determined by manual inspection.

Run: python3 scripts/compose-helmet-hero.py
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "src/assets/helmet-hero-base.jpg"
LOGO = ROOT / "src/assets/logo-source.png"
OUT = ROOT / "src/assets/helmet-hero.jpg"

# Anchor on the helmet crown in the 1920x1280 base image.
# Determined by manual inspection of helmet-hero-base.jpg.
CROWN_CENTER = (955, 610)   # (x, y) pixel center of the decal
DECAL_WIDTH = 360           # px — target width; height derived from aspect

def main() -> None:
    base = Image.open(BASE).convert("RGBA")
    logo = Image.open(LOGO).convert("RGBA")

    # Proportional resize — aspect ratio preserved.
    ratio = DECAL_WIDTH / logo.width
    target_h = round(logo.height * ratio)
    logo_resized = logo.resize((DECAL_WIDTH, target_h), Image.LANCZOS)

    # Slight opacity so the decal reads as printed on a curved surface,
    # rather than a flat sticker floating above it. This does not alter
    # the logo's shape or colors — it uniformly scales alpha.
    alpha = logo_resized.split()[3].point(lambda a: int(a * 0.92))
    logo_resized.putalpha(alpha)

    x = CROWN_CENTER[0] - DECAL_WIDTH // 2
    y = CROWN_CENTER[1] - target_h // 2

    canvas = base.copy()
    canvas.alpha_composite(logo_resized, dest=(x, y))
    canvas.convert("RGB").save(OUT, "JPEG", quality=92, optimize=True)
    print(f"wrote {OUT.relative_to(ROOT)}  ({canvas.size[0]}x{canvas.size[1]})")

if __name__ == "__main__":
    main()
